# Website

title: lnagb.js
# url: https://cgcentral.github.io/lnagb.js
theme: jekyll-theme-primer

# SEO

tagline: Educational linear algebra environment powered by the Web
description: Educational linear algebra environment powered by the Web
logo: logo.web.png
author:
  name: Novak
  email: novakcgx@protonmail.com
social:
  name: lnagb.js
  links:
    - https://cgcentral.github.io/lnagb.js

# Plugins

plugins:
    - jekyll-seo-tag

# Jekyll

exclude: [bundle,node_modules]

defaults:
  -
    scope:
      path: "download"
    values:
      section: "Download"
  -
    scope:
      path: "doc"
    values:
      section: "Documentation"
  -
    scope:
      path: "classroom"
    values:
      section: "Classroom"
  -
    scope:
      path: "lab"
    values:
      section: "Lab"
  -
    scope:
      path: "wiki"
    values:
      section: "Wiki"

disable_disk_cache: true
