# Website

title: lnagb.js
# url: https://cgcentral.github.io/lnagb.js
theme: jekyll-theme-primer

# SEO

tagline: Linear Algebra in a JavaScript library
description: Linear Algebra in a JavaScript library
logo: logo.web.png
author:
  name: Nguyen Hoang Duong
  email: novakcgx@protonmail.com
social:
  name: lnagb.js
  links:
    - https://cgcentral.github.io/lnagb.js

# Plugins

plugins:
    - jekyll-seo-tag

# Jekyll

exclude: [bundle,node_modules]

defaults:
  -
    scope:
      path: "docs"
    values:
      area: "Docs"
  -
    scope:
      path: "learn"
    values:
      area: "Learning Area"
  -
    scope:
      path: "lab"
    values:
      area: "Lab"
  -
    scope:
      path: "builds"
    values:
      area: "Builds"

disable_disk_cache: true
