# Website

title: lnagb.js
url: https://vecma-org.github.io/lnagb.js
baseurl: https://vecma-org.github.io/lnagb.js
theme: jekyll-theme-primer

# SEO

tagline: Linear Algebra in a JavaScript library
description: Linear Algebra in a JavaScript library
logo: logo.web.png
author:
  name: Nguyen Hoang Duong
  email: you_create@protonmail.com
social:
  name: lnagb.js
  links:
    - https://vecma-org.github.io/lnagb.js

# Plugins

plugins:
    - jekyll-seo-tag

# Jekyll

exclude: [bundle]

defaults:
  -
    scope:
      path: "docs"
    values:
      area: "Docs"
  -
    scope:
      path: "learn"
    values:
      area: "Learning Area"
  -
    scope:
      path: "lab"
    values:
      area: "Lab"

disable_disk_cache: true
